# Generated by Django 3.1.4 on 2021-01-16 18:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2021, 1, 16)),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(default=datetime.date(2021, 1, 16)),
        ),
        migrations.AlterField(
            model_name='warehouse_description',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2021, 1, 16)),
        ),
        migrations.AlterField(
            model_name='warehouse_description',
            name='updated_at',
            field=models.DateTimeField(default=datetime.date(2021, 1, 16)),
        ),
        migrations.AlterField(
            model_name='warehouse_description',
            name='warehouse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='warehouseApi.warehouse'),
        ),
    ]
