# Generated by Django 3.1.4 on 2021-01-16 18:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseApi', '0002_auto_20210116_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 18, 12, 30, 548991, tzinfo=utc)),
        ),
    ]
