# Generated by Django 3.1.4 on 2021-01-16 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseApi', '0005_auto_20210116_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse_description',
            name='warehouse_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='description', to='warehouseApi.warehouse'),
        ),
    ]
