# Generated by Django 3.1.4 on 2021-01-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseApi', '0006_auto_20210116_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
